# NumPy ndarray object

An array object that represents a **multidimensional**, **homogeneous** array of **fixed-size** items

## Create Methods

In [218]:
import numpy as np

### Create N dimensional arrays:

By literal - note that the number of opening squares equals the dimension

In [219]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

Create array filled with random values: __np.empty__ of type __np.int8__

In [220]:
b = np.empty( (3,2), dtype=np.int8  )
b

array([[0, 1],
       [0, 0],
       [0, 0]], dtype=int8)

Create array by __np.arange()__ method (quite simmilar to python's __range()__)

In [221]:
b = np.arange(0,21,2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## Basic Properties:

### shape - tuple of array dimensions

In [222]:
a1.shape

(3, 3)

### ndim - number of array dimensions

In [223]:
a1.ndim

2

### dtype - data-type of the array’s elements

In [224]:
a1.dtype

dtype('int64')

### size - number of elements in the array

In [225]:
a1.size

9

### itemsize - length of one array element in bytes.

In [226]:
a1.itemsize

8

### nbytes - total bytes consumed by the elements of the array

In [227]:
a1.nbytes

72

## Arrays Algebra (Element Wise)

In [228]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print("The result of a+2 is:")
print(a+2)
print("The result of a+b is:")
print(a+b)

The result of a+2 is:
[[3 4 5]
 [6 7 8]]
The result of a+b is:
[[ 2  4  6]
 [ 8 10 12]]


#### matrix product: __dot()__ 

In [229]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2],[3,4],[5,6]])

a.dot(b)

array([[22, 28],
       [49, 64]])

In [230]:
b.dot(a)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

#### Comparison operators

In [231]:
# compare array with single value:
a = np.array([1,2,3])
print(a<2)

# compare array with array (with same shape):
b = np.array([4,5,1])
print(a < b)


[ True False False]
[ True  True False]


## Indexing and slicing

### One-dimensional arrays

In [232]:
a1 = np.arange(1,10)
print(a1)

print("\npositive index - from left to right - a1[1]")
print(a1[1])

print("\nnegative index - from right to left - a1[-1]")
print(a1[-1])

print("\nget elements with indexes 0 upto 3 (excluded) - a1[0:3]")
print(a1[0:3])

print("\nget all elements - a1[:]")
print(a1[:])

print("\nget all elements, without the last one - a1[:-1]")
print(a1[:-1])

print("\nslicing with step - a1[0:9:2]")
print(a1[0:9:2])

print("\nslicing with step - backwards - a1[-1::-2]")
print(a1[-1::-2])

[1 2 3 4 5 6 7 8 9]

positive index - from left to right - a1[1]
2

negative index - from right to left - a1[-1]
9

get elements with indexes 0 upto 3 (excluded) - a1[0:3]
[1 2 3]

get all elements - a1[:]
[1 2 3 4 5 6 7 8 9]

get all elements, without the last one - a1[:-1]
[1 2 3 4 5 6 7 8]

slicing with step - a1[0:9:2]
[1 3 5 7 9]

slicing with step - backwards - a1[-1::-2]
[9 7 5 3 1]


### Multi dimensional arrays

In [233]:
# let's have the array:
a1 = np.arange(1,10).reshape(3,3)
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [234]:
# get an element with tupple index
a[1,2]

IndexError: too many indices for array

In [ ]:
# get an element with indx chaining index
a[1][2]

**Note: index chaining returns the same result, but is more inefficient as a new temporary array is created after the first index that is subsequently indexed by 2.**

Let's do some slicing

In [ ]:
print("\nSlice the first row - a1[0,:]")
print(a1[0,:])

print("\nSlice the first column - a1[:,0]")
print(a1[:,0])

print("\nSlice first 2 rows and columns - a1[0:2, 0:2]")
print(a1[0:2, 0:2])

### Boolean indexing

We can select certain values from a numpy array, if we mask it with a Boolean array (True/False values) with the **same shape**

In [ ]:
# this is the original array:
a = np.arange(1,6)
print(a)

# this is the mask:
mask = [True, True, False, True, False]

# lets apply the mask:
print(a[mask])

#### Masking example 1 : select only the even values

In [ ]:
# let's have a bigger array:
a = np.arange(1,20)

# and get only even numbers from it:
a[a%2==0]

How it works:

a%2 is calculated for each element of the array.

If result value, which serves as index, is True => the element is selected, 
if it is False the element is not selected 

#### Masking example 2 : map list elements to array of indexes

In [238]:
# let's have a numpy array of repeated values 0, 1 or 2:
indexes = np.array([0, 2, 1, 2, 0, 1,2])

# and a list of colors:
colors = ['red', 'green', 'blue']

# let's group the elements of the 'indexes' array by color, according to 
# their values, which will be used as indexes in colors list
# For simplicity, we'll just print the groups, but if we need, we can save them in dictionary
for i in range(len(colors)):  
    print(f"{colors[i]} group:")
    print(indexes[indexes==i])
    

red group:
[0 0]
green group:
[1 1]
blue group:
[2 2 2]


#### Masking example 2 : group 'scores' by category

Let's have an array of 'scores', and for each score we'll have to assign a category from a predefined list. So, we'll add to each score element the index of the category list.
The goal is to group scores by category.

In [ ]:
scores = np.array([
    [4, 1],
    [2, 0],
    [3, 0],
    [5, 1],
    [6, 1]
])

categories = ['bad', 'good']


for i in range(len(categories)):  
    # make the mask:
    mask = scores[:,1] == i
    print(mask)
    
    # now apply it to scores:
    print(f"{categories[i]} scores are:")
    print(scores[:,0][mask])

## Array Manipulations

#### Flatten the array

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel()

#### reshaping arrays: __np.reshape()__

In [ ]:
a = np.arange(1,10)
a

In [ ]:
a.reshape(3,3)

In [ ]:
a.reshape(1,9)